run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false

  govet:
    enable-all: false
    enable:
      - shadow
      - printf
      - structtag
      - unreachable

  misspell:
    locale: US

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    # Silence all comment/export doc warnings
    - linters:
        - golint
        - revive
        - staticcheck
      text: "should have comment|comment on exported|ST1000|ST1020"

    # Silence fieldalignment
    - linters:
        - govet
      text: "fieldalignment"
